### ISSUE TITLE
Japanese article about Milk-V Duo

### ISSUE THREAD

**Issue by MilkVNaoki** [sophgocommunity/SG2042-Newsletter#125]
as I noted [here](https://github.com/sophgocommunity/SG2042-Newsletter/commit/24898ba617232de7622fe854fe27eed90533019a#r142299991), there is [article about Milk-V Duo in Japanese](https://gihyo.jp/admin/serial/01/ubuntu-recipe/0814).
it would be happy if you could add this article to your newsletter.

**Comment by JoannaWu84** [comment]
Thanks for your contribution:) I will add this article to the #044 newsletter which will be published this Friday.
